name: 'Infostart-articles'
description: 'Формирование списка последних статей Инфостарт для профиля GitHub'
inputs:
  profile-id: 
    description: 'ID профиля'
    required: true
  readme-file:
    description: 'Путь к Readme файлу. По умолчанию - ./README.md'
    required: false
    default: './README.md'
  count: 
    description: 'Количество выводимых статей. По умолчанию - 3'
    required: false
    default: '3'
runs:
  using: "composite"
  steps:
    - name: Чекаут
      run: echo "Yo"

