name: 'Infometrics-articles'
branding:
  icon: 'user'
  color: 'blue'
description: 'Формирование списка последних статей Инфостарт для профиля GitHub'
inputs:
  profile-id: 
    description: 'ID профиля'
    required: true
  readme-file:
    description: 'Путь к Readme файлу. По умолчанию - ./README.md'
    required: false
    default: './README.md'
  count: 
    description: 'Количество выводимых статей. По умолчанию - 3'
    required: false
    default: '3'
  template:
    description: |
      Текстовый шаблон одной статьи. Переменные: 
          %1 - URL изображения
          %2 - Заголовок статьи
          %3 - Ссылка на статью
          %4 - Число звезд
          %5 - Описание статьи
          %6 - Дата статьи
          %7 - Комментарии
          %8 - Просмотры

          Шаблон по умолчанию

          > <img src=""%1"" width=""96"" align=""left"">\n   
          > <h4 style=""color: white;""><a href=""%3"">%2</a></h4>\n
          > <small>%5</small>\n  
          > <br clear=""left"">\n
          > \n
          > | :star: %4 |  :calendar: %6 |  :speech_balloon: %7 |  :eyes: %8 |\n
          > |-|-|-|-|\n 

    required: false
    default: '""'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4 
    - name: OneScript
      uses: otymko/setup-onescript@v1.4
      with:
        version: 1.9.0 
    - name: Запуск скрипта
      run: oscript ${{ github.action_path }}/update.os ${{ inputs.profile-id }} ${{ inputs.readme-file }} ${{ inputs.count }} ${{ inputs.template }}
      shell: bash
    - name: Запись изменений
      uses: stefanzweifel/git-auto-commit-action@v5   
      with:
        commit_user_name: Vitaly the Alpaca (bot) 
        commit_user_email: vitaly.the.alpaca@gmail.com
        commit_author: Vitaly the Alpaca <vitaly.the.alpaca@gmail.com>
        commit_message: Обновление списка статей Инфостарт в Readme (bot)

