name: Test
on:
  workflow_dispatch:
jobs:
  RunOneScript:
    runs-on: ubuntu-latest 
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./action.yml
        with:
          profile-id: '1793672'
